version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/RAGHT2.0

hooks:
  BeforeInstall:
    - location: before_script.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: after_script.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ubuntu
