---
version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/html/HT2.0-RAG/
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/before_script.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/after_scripts.sh
      timeout: 300
      runas: root
