version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running before_script.sh..."
      - chmod +x scripts/before_script.sh
      - ./scripts/before_script.sh

    build:
    commands:
      - echo "Creating Python virtual environment..."
      - python3 -m venv venv || { echo "Virtual environment creation failed"; exit 1; }
      - ls -l venv/  # Debugging step to verify venv exists
      - echo "Activating virtual environment..."
      - source venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt || { echo "Dependency installation failed"; exit 1; }

  post_build:
    commands:
      - echo "Running after_scripts.sh..."
      - chmod +x scripts/after_scripts.sh
      - ./scripts/after_scripts.sh || { echo "Post-deployment script failed"; exit 1; }
      - echo "Build and deployment steps completed."

artifacts:
  files:
    - '**/*'
  discard-paths: no
