version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking Python version..."
      - python3 --version || { echo "Python3 not found"; exit 1; }
      - echo "Creating virtual environment..."
      - python3 -m venv venv || { echo "Failed to create venv"; exit 1; }
      - echo "Fixing permissions for venv..."
      - chmod -R 755 venv

  build:
    commands:
      - echo "Activating virtual environment..."
      - bash -c "source venv/bin/activate" || { echo "Failed to activate venv"; exit 1; }
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  post_build:
    commands:
      - echo "Restarting application..."
      - chmod +x after_script.sh
      - ./after_script.sh || { echo "after_script.sh execution failed"; exit 1; }

artifacts:
  files:
    - '**/*'
  discard-paths: no
