version: 0.2

phases:
    pre_build:
    commands:
      - echo "Checking directory structure..."
      - ls -R  # List all directories and files
      - if [ -d scripts ]; then echo "scripts directory found"; else echo "scripts directory missing"; exit 1; fi
      - ls -l scripts/  # List files in the scripts directory

  build:
    commands:
      - echo "Creating Python virtual environment..."
      - python3 -m venv venv
      - source venv/bin/activate
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - deactivate  # Deactivate venv after installation

  post_build:
    commands:
      - echo "Running after_scripts.sh..."
      - if [ -f scripts/after_scripts.sh ]; then chmod +x scripts/after_scripts.sh; fi
      - ./scripts/after_scripts.sh
      - echo "Build and deployment steps completed."

artifacts:
  files:
    - '**/*'
    - 'scripts/**'
  discard-paths: no
