version: 0.2

phases:
    pre_build:
    commands:
      - echo "Listing all files in the workspace..."
      - ls -l
      - echo "Checking if after_script.sh exists..."
      - ls -l after_script.sh || { echo "after_script.sh is missing!"; exit 1; }

  build:
    commands:
      - echo "Activating virtual environment..."
      - bash -c "source venv/bin/activate" || { echo "Failed to activate venv"; exit 1; }
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

    post_build:
    commands:
      - echo "Setting execute permission on after_script.sh..."
      - chmod +x /var/www/html/RAGHT2.0/after_script.sh || { echo "Failed to set permissions"; exit 1; }
      - echo "Executing after_script.sh..."
      - /var/www/html/RAGHT2.0/after_script.sh

artifacts:
  files:
    - '**/*'
  discard-paths: no
