version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking if before_script.sh exists in the current directory..."
      - ls -l  # List all files to debug
      - if [ -f before_script.sh ]; then echo "before_script.sh found"; else echo "before_script.sh missing"; exit 1; fi
      - echo "Setting execute permission for before_script.sh..."
      - chmod +x before_script.sh
      - ./before_script.sh

  build:
    commands:
      - echo "Creating Python virtual environment..."
      - python3 -m venv venv
      - source venv/bin/activate
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - deactivate  # Deactivate venv after installation

  post_build:
    commands:
      - echo "Checking if after_scripts.sh exists..."
      - ls -l  # List all files to debug
      - if [ -f after_scripts.sh ]; then chmod +x after_scripts.sh; fi
      - ./after_scripts.sh
      - echo "Build and deployment steps completed."

artifacts:
  files:
    - '**/*'
  discard-paths: no
