version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running pre-build phase..."
      - chmod +x before_script.sh || { echo "Failed to set permissions for before_script.sh"; exit 1; }
      - ./before_script.sh

  build:
    commands:
      - echo "Creating Python virtual environment..."
      - python3 -m venv venv
      - source venv/bin/activate || { echo "Failed to activate venv"; exit 1; }
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  post_build:
    commands:
      - echo "Running post-build phase..."
      - chmod +x after_script.sh || { echo "Failed to set permissions for after_script.sh"; exit 1; }
      - ./after_script.sh
      - echo "Build and deployment steps completed."

artifacts:
  files:
    - '**/*'
  discard-paths: no
