version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking available directories..."
      - ls -l
      - echo "Ensuring before_script.sh is executable..."
      - chmod +x ./before_script.sh || { echo "Failed to set permissions for before_script.sh"; exit 1; }
      - echo "Running before_script.sh..."
      - ./before_script.sh || { echo "before_script.sh execution failed"; exit 1; }

  build:
    commands:
      - echo "Creating Python virtual environment..."
      - python3 -m venv venv || { echo "Failed to create venv"; exit 1; }
      - echo "Activating virtual environment..."
      - source venv/bin/activate || { echo "Failed to activate venv"; exit 1; }
      - echo "Installing dependencies..."
      - pip install --upgrade pip setuptools wheel
      - pip install -r requirements.txt || { echo "Dependency installation failed"; exit 1; }

    post_build:
    commands:
      - echo "Checking available files..."
      - ls -l
      - echo "Ensuring after_script.sh is executable..."
      - chmod +x after_script.sh || { echo "Failed to set permissions for after_script.sh"; exit 1; }
      - echo "Running after_script.sh..."
      - ./after_script.sh || { echo "after_script.sh execution failed"; exit 1; }
      - echo "Build and deployment steps completed."

artifacts:
  files:
    - '**/*'
  discard-paths: no

