version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking available directories..."
      - ls -l
      - echo "Ensuring before_script.sh is executable..."
      - chmod +x before_script.sh || { echo "Failed to set permissions"; exit 1; }
      - echo "Running before_script.sh..."
      - ./before_script.sh || { echo "before_script.sh execution failed"; exit 1; }

  build:
    commands:
      - echo "Creating Python virtual environment..."
      - python3 -m venv venv
      - source venv/bin/activate
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  post_build:
    commands:
      - echo "Ensuring after_script.sh is executable..."
      - chmod +x after_script.sh || { echo "Failed to set permissions"; exit 1; }
      - echo "Running after_script.sh..."
      - ./after_script.sh || { echo "after_script.sh execution failed"; exit 1; }
      - echo "Build and deployment steps completed."

artifacts:
  files:
    - '**/*'
  discard-paths: no
