version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking if scripts/before_script.sh exists..."
      - ls -l scripts/  # List files in scripts directory
      - if [ -f scripts/before_script.sh ]; then echo "File exists"; else echo "File does not exist"; exit 1; fi
      - echo "Setting execute permission for before_script.sh..."
      - chmod +x scripts/before_script.sh
      - ls -l scripts/  # Verify permissions after chmod
      - ./scripts/before_script.sh

  build:
    commands:
      - echo "Creating Python virtual environment..."
      - python3 -m venv venv
      - source venv/bin/activate
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - deactivate  # Deactivate venv after installation

  post_build:
    commands:
      - echo "Running after_scripts.sh..."
      - if [ -f scripts/after_scripts.sh ]; then chmod +x scripts/after_scripts.sh; fi
      - ./scripts/after_scripts.sh
      - echo "Build and deployment steps completed."

artifacts:
  files:
    - '**/*'
  discard-paths: no

